### ISSUE TITLE
skonfig -V fails when it shouldn't

### ISSUE THREAD

**Issue by 4nd3r** [skonfig/skonfig#38]
```
$ python3 -V
Python 3.10.6
$ git tag 1.2.3 -m test
$ git diff
diff --git a/skonfig/version.py b/skonfig/version.py
index 9c18fbd8..e2acfc35 100644
--- a/skonfig/version.py
+++ b/skonfig/version.py
@@ -32,7 +32,7 @@ def __guess_git_version():
                     else "",
                 run(["git", "describe", "--tags", "--dirty",
                      "--abbrev=7", "--match=[0-9]*"]))
-        except Exception:
+        except KeyboardInterrupt:
             pass
 
     return "unknown version"
$ skonfig -V
Traceback (most recent call last):
  File "/home/ander/.local/bin/skonfig", line 12, in <module>
    import skonfig
  File "/home/ander/Desktop/skonfig/skonfig/skonfig/__init__.py", line 7, in <module>
    from skonfig.version import VERSION as __version__
  File "/home/ander/Desktop/skonfig/skonfig/skonfig/version.py", line 41, in <module>
    VERSION = __guess_git_version()
  File "/home/ander/Desktop/skonfig/skonfig/skonfig/version.py", line 33, in __guess_git_version
    run(["git", "describe", "--tags", "--dirty",
  File "/home/ander/Desktop/skonfig/skonfig/skonfig/version.py", line 16, in run
    with os.open(os.devnull, os.O_RDONLY) as devnull:
AttributeError: __enter__
```

I quickly replaced `except Exception` with something so I could see error :smile: 

When I remove `with os.open(os.devnull, os.O_RDONLY) as devnull:` etc, then it works.

Looking at this now (after the PR merge :smile:), this version guessing feels bit overengineered and it took multiple reads before I understood what's going on. Can we make it bit more readable?

**Comment by sideeffect42** [comment]
Using `os.open` as a context manager is indeed incorrect. Must've been late when I wrote that code ;-)
