### ISSUE TITLE
Cleanup fails

### ISSUE THREAD

**Issue by fancsali** [skonfig/skonfig#52]
Running `skonfig`, everything seems to go fine, until the code tries to remove some temporary files (the `/var/lib/skonfig` directory, to be more specific):

```
 ERROR: v2202005121729118108.happysrv.de: ssh -o User=root -o ControlPath=/data/data/com.termux/files/usr/tmp/tmpr8k8y2v0/s -o ControlMaster=auto -o ControlPersist=2h my.host.name rm -rf /var/lib/skonfig: ['ssh', '-o', 'User=root', '-o', 'ControlPath=/data/data/com.termux/files/usr/tmp/tmpr8k8y2v0/s', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=2h', 'my.host.name', 'rm', '-rf', '/var/lib/skonfig']
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/opt/skonfig/cdist/exec/remote.py", line 311, in _run_command
    subprocess.check_call(command, env=os_environ, stdout=stdout,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-o', 'User=root', '-o', 'ControlPath=/data/data/com.termux/files/usr/tmp/tmpr8k8y2v0/s', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=2h', 'my.host.name', 'rm', '-rf', '/var/lib/skonfig']' returned non-zero exit status 255.
```

**Comment by fancsali** [comment]
Confirmed the same behaviour is present on a RaspberryPi, running Raspberry Pi OS 11.4 (bullseye); with kernel 5.15.61 running on 32-bit ARM (armv7l).

**Comment by sideeffect42** [comment]
TBH, I'm not sure if this is a skonfig error and if, how we could debug this without replicating your exact setup and state of the moon :-/

Removing the working dir on the target is done twice in a config run (at the very beginning to ensure a clean working dir and at the very end to clean up «after ourselves»).

I understand that in your case the config run runs through all the objects and then fails at the very last step when trying to clean up the working directory?
If so, you could try to run skonfig with `-vv` to skip the final clean up (cf. [`skonfig/cdist/__init__.py:35`](https://github.com/skonfig/skonfig/blob/1fb9573/skonfig/cdist/__init__.py#L35)).

**Comment by fancsali** [comment]
Well, I appreciate I've got somewhat exotic setup with Termux, however it seems to be present on bog standard RaspberryPi with the **official stable** Debian based OS. So, I am inclined to say, whatever is causing it, it will be an issue for others too.

Besides, I am confused: with `-vv` the issue is gone, perhaps it won't run the cleanup, as you suggest; however with `-vvv` it's there, but it only seems to do the `rm -rf` at the end of the configuration run.

On yet another note, it seems to be intermittent now; will do further investigation...

**Comment by fancsali** [comment]
A bit of additional info, just for the record:

- Everything seems to be fine, if I run something simple, like `echo "__cdistmarker" | skonfig -i - my.host.name`
- I seem to experience the issue on longer runs
- When it happens, ssh seems to be returning exit code 255:
```
...
subprocess.CalledProcessError: Command '['ssh', '-o', 'User=root', '-o', 'ControlPath=/tmp/tmpkitlpcg1/s', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=2h', 'my.host.name', 'rm', '-rf', '/var/lib/skonfig']' returned non-zero exit status 255.
...
```

which in turn seems to be a "general error" reported by SSH (as opposed to an error reported by the command called via SSH): https://man.openbsd.org/ssh#EXIT_STATUS

**Comment by 4nd3r** [comment]
I ran complex manifest in loop from RPi to RPi for several hours. Can't repro :disappointed:

**Comment by fancsali** [comment]
I did some digging, and managed to uncover some further details.

Long story short, I've got [fwknop](https://www.cipherdyne.org/fwknop/) set up on my server for some extra defence in depth via port-knocking.

Thanks to the persistent connection feature (`ControlPersist` and `ControlMaster`) the whole config run is completely fine if I do one single knock before kicking off `skonfig`.

However, the final cleanup only succeeds, if I keep knocking while `skonfig` is running.

Thus, I suspect, the initial connection is used for all subsequent operations, except the cleanup.

I just wonder: is this by design, or is it something that's caused by `-o ControlPersist auto` **thinking** the old connection is dead, and trying to open a new one...

**Comment by sideeffect42** [comment]
@fancsali Could you please check if #60 resolves this problem for you?
